### ISSUE TITLE
::sendmmsg has not been declared

### ISSUE THREAD

**Issue by molixiaoge** [samanbarghi/uThreads#31]
I download 0.3 release src,and build with gcc 4.9.2.Run make in the root directory,and the error shows `'src/io/Network.cpp:232:15: error: ‘::sendmmsg’ has not been declared` .And i serach the code,then i replace `::sendmmsg with sendmmsg` ,it make ok.

**Comment by samanbarghi** [comment]
Hi, Thanks for letting me know. Can I ask which version of glibc you are using? since this is only happening for sendmmsg and not other methods in class Network, I suspect you have a glibc version older than 2.14 and thus need to make a call to the system call. (http://man7.org/linux/man-pages/man2/sendmmsg.2.html). Please let me know the version of glibc you are using and I probably need to fix this to be compatible with older versions of glibc. Thanks.

**Comment by molixiaoge** [comment]
Yes,you are right! My glibc version is  `(GNU libc) 2.12`.My gcc 4.9.2 is installed by `devtoolset-3-toolchain` (and i also have gcc 4.4.7).The reason is gcc 4.9.2 use the old glibc 2.12.

Thanks ,for your reply!

**Comment by samanbarghi** [comment]
Thanks a lot for getting back to me, I will address this issue soon :+1:
